package entities;

import java.util.Date;

/**
 * Aquilados generated by hbm2java
 */
public class Aquilados  implements java.io.Serializable {


     private Integer idaquilado;
     private Cliente cliente;
     private Veiculo veiculo;
     private Date fecha;
     private String status;

    public Aquilados() {
    }

    public Aquilados(Cliente cliente, Veiculo veiculo, Date fecha, String status) {
       this.cliente = cliente;
       this.veiculo = veiculo;
       this.fecha = fecha;
       this.status=status;
    }
   
    public Integer getIdaquilado() {
        return this.idaquilado;
    }
    
    public void setIdaquilado(Integer idaquilado) {
        this.idaquilado = idaquilado;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Veiculo getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}


