package entities;
// Generated Mar 27, 2018 10:35:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String nombre;
     private String apellido;
     private String email;
     private String contrasena;
     private Set aquiladoses = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nombre, String apellido, String email, String contrasena) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.contrasena = contrasena;
    }
    public Cliente(String nombre, String apellido, String email, String contrasena, Set aquiladoses) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.contrasena = contrasena;
       this.aquiladoses = aquiladoses;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getAquiladoses() {
        return this.aquiladoses;
    }
    
    public void setAquiladoses(Set aquiladoses) {
        this.aquiladoses = aquiladoses;
    }

    @Override
    public String toString() {
        return "Cliente{" + "idcliente=" + idcliente + ", nombre=" + nombre + ", apellido=" + apellido + ", email=" + email + ", contrasena=" + contrasena + ", aquiladoses=" + aquiladoses + '}';
    }




}


