package entities;
// Generated Mar 27, 2018 10:35:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Veiculo generated by hbm2java
 */
public class Veiculo  implements java.io.Serializable {


     private Integer idveiculo;
     private String marca;
     private String modelo;
     private String status;
     private String url;
     private String categoria;
     private float price;
     private String information;
     private Set aquiladoses = new HashSet(0);

    public Veiculo() {
    }

    public Veiculo(Integer idveiculo, String marca, String modelo, String status, String url, String categoria, float price, String information) {
        this.idveiculo = idveiculo;
        this.marca = marca;
        this.modelo = modelo;
        this.status = status;
        this.url = url;
        this.categoria = categoria;
        this.price = price;
        this.information = information;
    }
    
     public Veiculo(Integer idveiculo, String marca, String modelo, String status, String url, String categoria, float price, String information,Set aquiladoses) {
        this.idveiculo = idveiculo;
        this.marca = marca;
        this.modelo = modelo;
        this.status = status;
        this.url = url;
        this.categoria = categoria;
        this.price = price;
        this.information = information;
         this.aquiladoses = aquiladoses;
    }
   
    public Integer getIdveiculo() {
        return this.idveiculo;
    }
    
    public void setIdveiculo(Integer idveiculo) {
        this.idveiculo = idveiculo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getAquiladoses() {
        return this.aquiladoses;
    }
    
    public void setAquiladoses(Set aquiladoses) {
        this.aquiladoses = aquiladoses;
    }

    public String getCategoria() {
        return categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public String getInformation() {
        return information;
    }

    public void setInformation(String information) {
        this.information = information;
    }




}


